const menu=document.querySelector('.menu');const nav=document.querySelector('#navigation');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open')){menu.setAttribute('aria-expanded','false');nav.classList.remove('open');menu.focus()}});nav?.addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}});
function calculateCloud(v){return {'GPU compute':v.gpus*v.gpuRate*v.hours,'VMs / worker nodes':v.vms*v.vmRate*v.hours,'Kubernetes cluster fees':v.clusters*v.clusterRate,'Block storage':v.block*v.blockRate,'Object storage':v.object*v.objectRate,'Database instances':v.db*v.dbRate,'Outbound transfer':v.egress*v.egressRate};}
const form=document.querySelector('#calculator');const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});function updateEstimate(){if(!form)return;const valid=form.checkValidity();document.querySelector('#calc-error').textContent=valid?'':'Enter non-negative values within the allowed limits. Compute hours cannot exceed 744.';if(!valid){document.querySelector('#total').textContent='—';document.querySelector('#breakdown').replaceChildren();return;}const values=Object.fromEntries([...form.querySelectorAll('input')].map(el=>[el.id,Number(el.value)]));const rows=calculateCloud(values);document.querySelector('#total').textContent=money.format(Object.values(rows).reduce((a,b)=>a+b,0));document.querySelector('#breakdown').innerHTML=Object.entries(rows).map(([name,cost])=>`<div class="bill-row"><span>${name}</span><strong>${money.format(cost)}</strong></div>`).join('');return {currency:'USD',monthlyTotal:Object.values(rows).reduce((a,b)=>a+b,0),breakdown:rows,illustrative:true};}if(form){form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',updateEstimate);form.addEventListener('reset',()=>setTimeout(updateEstimate,0));updateEstimate();}
if(form&&document.modelContext?.registerTool){const lifecycle=new AbortController();const inputs=[...form.querySelectorAll('input')];const properties=Object.fromEntries(inputs.map(el=>[el.id,{type:'number',minimum:Number(el.min),maximum:Number(el.max),...(el.step==='1'?{multipleOf:1}:{})}]));try{Promise.resolve(document.modelContext.registerTool({name:'configure_cloud_estimate',title:'Configure cloud cost estimate',description:'Update resource quantities or example USD unit rates and return the visible monthly estimate. Does not purchase services.',inputSchema:{type:'object',properties,additionalProperties:false},annotations:{readOnlyHint:false},execute(data){if(!data||typeof data!=='object'||Array.isArray(data))throw new Error('Expected an object');for(const [key,value] of Object.entries(data)){const el=inputs.find(el=>el.id===key);if(!el||typeof value!=='number'||!Number.isFinite(value)||value<Number(el.min)||value>Number(el.max)||Math.abs(value/Number(el.step)-Math.round(value/Number(el.step)))>1e-6)throw new Error('Invalid field: '+key);}for(const [key,value] of Object.entries(data))form.elements.namedItem(key).value=String(value);return updateEstimate();}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

// Motion is progressive enhancement: all content is visible without JavaScript.
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const revealTargets=[...document.querySelectorAll('.section-top, .platform-section .card, .split>div, .principles .card, .featured, .page-blog .pale .card, .callout')];
if(!reducedMotion.matches&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');entry.target.classList.remove('reveal-pending');observer.unobserve(entry.target)}})},{threshold:0.07});revealTargets.forEach((el,i)=>{if(el.getBoundingClientRect().top>window.innerHeight){el.classList.add('reveal','reveal-pending');el.style.setProperty('--reveal-delay',`${Math.min(i%3*65,130)}ms`);observer.observe(el)}});reducedMotion.addEventListener('change',e=>{if(e.matches){observer.disconnect();revealTargets.forEach(el=>el.classList.remove('reveal-pending'))}});}
const readingArticle=document.querySelector('.prose');let progressBar;if(readingArticle){progressBar=document.createElement('div');progressBar.className='reading-progress';progressBar.setAttribute('aria-hidden','true');document.body.append(progressBar);}
let scrollQueued=false;function updateScrollState(){document.body.classList.toggle('scrolled',window.scrollY>12);if(readingArticle){const rect=readingArticle.getBoundingClientRect();const length=Math.max(1,rect.height-window.innerHeight+150);progressBar.style.transform=`scaleX(${Math.max(0,Math.min(1,(150-rect.top)/length))})`;const sections=[...readingArticle.querySelectorAll('h2[id]')];const active=sections.filter(el=>el.getBoundingClientRect().top<190).at(-1);document.querySelectorAll('.toc a').forEach(link=>{const selected=link.hash==='#'+active?.id;link.classList.toggle('active',selected);if(selected)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')})}scrollQueued=false;}window.addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(updateScrollState)}},{passive:true});updateScrollState();
if(form){let animateTimer;form.addEventListener('change',()=>{if(reducedMotion.matches)return;const summary=document.querySelector('.summary');summary.classList.remove('updated');requestAnimationFrame(()=>{summary.classList.add('updated');clearTimeout(animateTimer);animateTimer=setTimeout(()=>summary.classList.remove('updated'),550)})});}
